## Write a Numpy program to compute the multiplication of two given matrixes

In [1]:
import numpy as np

In [2]:
m1=[[1,2],[3,4]]   #first matrix (2,2)
m2=[[2,2],[3,3]]   #second matrix (2,2)

np.dot(m1,m2)      #dot ==> multiplication of m1 and m2

array([[ 8,  8],
       [18, 18]])

## Write a NumPy program to compute the determinant of a given square array

In [12]:
#square array = martrix (2*2)
np.linalg.det(np.array([[1,2],[3,4]]))  #(np.linlag.det) ==> to get the determinate of the matrix created by (np.array)

-2.0000000000000004

## Write a NumPy program to compute the cross product of two given vectors

In [3]:
m1=[[1,2],[3,4]]     #first matrix (2,2)
m2=[[2,2],[3,3]]     #second matrix (2,2)

np.cross(m1,m2)      #cross==> cross product of m1 and m2

array([-2, -3])

## Write a NumPy program to compute the condition number of a given matrix

In [6]:
from numpy import linalg as LA                       #linlag ==> linear algibra 

LA.cond(np.array([[1, 2, 2], [3, 4, 5], [6, 7, 8]])) #cond ==> to get the condition number

44.61039731263847

## Write a NumPy program to compute the inverse of a given matrix

In [8]:
np.linalg.inv(np.array([[1,2],[3,4]]))   #inv==> to get the inverse of the matrix

array([[-2. ,  1. ],
       [ 1.5, -0.5]])